apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-expired-deployments
spec:
  schedule: "*/1 * * * *"  # Runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: delete-expired-deployments
              image: kubectl:latest
              command:
                - "sh"
                - "-c"
                - |
                  kubectl get deployments -o=jsonpath='{range .items[*]}{.metadata.name} {.metadata.annotations.lifespan} {"\n"}{end}' |
                  while read deployment lifespan; do
                    if [ "$lifespan" != "" ]; then
                      lifespan_seconds=$(date -d "$lifespan" +%s)
                      creation_timestamp=$(kubectl get deployment $deployment -o=jsonpath='{.metadata.creationTimestamp}')
                      creation_seconds=$(date -d "$creation_timestamp" +%s)
                      current_time=$(date +%s)
                      if [ $((current_time - creation_seconds)) -ge $lifespan_seconds ]; then
                        kubectl delete deployment $deployment
                      fi
                    fi
                  done
          restartPolicy: OnFailure
