apiVersion: v1
kind: Service
metadata:
  name: branch-deploy-master-service
spec:
  selector:
    app: branch-deploy-master
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
