apiVersion: apps/v1
kind: Deployment
metadata:
  name: branch-deploy-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: branch-deploy-application
  template:
    metadata:
      labels:
        app: branch-deploy-application
    spec:
      containers:
        - name: branch-deploy-application
          image: dvdty/branch-deploy-application:test
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
